#!/bin/bash
cd $HOME/GitHub/visbo-server-ui
echo "01: Checking Local Status of Visbo UI Branch"
git status
if [ $? -ne 0 ]
then
  echo "FATAL: Local Changes have to be checked first before upgrading."
  exit 1
fi

echo  "02: Pull Branch from Repository Server"
updateCmdOrg=`date -r update-ui '+%Y-%m-%dT%H:%M:%S'`
pullOutput=`git pull`

if [ $? -ne 0 ]
then
  echo "FATAL: Pull Failed to update Visbo UI  Branch."
  exit 1
fi

echo "Pull Result"
echo "$pullOutput"

updateCmdAct=`date -r update-ui '+%Y-%m-%dT%H:%M:%S'`
if [ "$updateCmdOrg" != "$updateCmdAct" ]
then
  echo "WARN: Update Script has changed in between, please restart update again."
  exit 2
fi

echo "05: Remove the Visbo UI Client from production directory"
rm -rf /var/www/visbo-web-ui/*
echo "06: Copy the Visbo UI Client to production directory"
cp -r dist/* /var/www/visbo-web-ui
find /var/www/visbo-web-ui -type d -exec chmod 755 {} +
find /var/www/visbo-web-ui -type f -exec chmod 644 {} +

echo "Visbo UI Client Updated Successfully"
